spring:
  flyway:
    locations: classpath:db/auth,db/dev/data/auth_{vendor},db/dev/data/auth

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
