spring:
  flyway:
    locations: classpath:db/migration/auth,db/migration/auth_{vendor},db/migration/dev/data/auth_{vendor},db/migration/dev/data/auth
    enabled: true

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
