spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  datasource:
    url: jdbc:postgresql://localhost:5432/auth-db
    username: admin
    password: admin_password

  h2:
    console:
      enabled: false
