---
# Per environment values which override defaults in hmpps-external-users-api/values.yaml

generic-service:
  ingress:
    host: external-users-api.hmpps.service.justice.gov.uk

  env:
    API_BASE_URL_OAUTH: https://sign-in.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_MANAGE_USERS: https://manage-users-api.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
